//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://careevolution.com/sample", ConfigurationName = "IContract", CallbackContract = typeof(IContractCallback))]
public interface IContract
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://careevolution.com/sample/IContract/Ping")]
    void Ping(string value);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://careevolution.com/sample/IContract/Ping")]
    System.Threading.Tasks.Task PingAsync(string value);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://careevolution.com/sample/IContract/Join")]
    void Join(string asName);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://careevolution.com/sample/IContract/Join")]
    System.Threading.Tasks.Task JoinAsync(string asName);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://careevolution.com/sample/IContract/Leave")]
    void Leave();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://careevolution.com/sample/IContract/Leave")]
    System.Threading.Tasks.Task LeaveAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IContractCallback
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://careevolution.com/sample/IContract/PingBack")]
    void PingBack(string result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IContractChannel : IContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ContractClient : System.ServiceModel.DuplexClientBase<IContract>, IContract
{

    public ContractClient(System.ServiceModel.InstanceContext callbackInstance) :
            base(callbackInstance)
    {
    }

    public ContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) :
            base(callbackInstance, endpointConfigurationName)
    {
    }

    public ContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) :
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public ContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public ContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(callbackInstance, binding, remoteAddress)
    {
    }

    public void Ping(string value)
    {
        base.Channel.Ping(value);
    }

    public System.Threading.Tasks.Task PingAsync(string value)
    {
        return base.Channel.PingAsync(value);
    }

    public void Join(string asName)
    {
        base.Channel.Join(asName);
    }

    public System.Threading.Tasks.Task JoinAsync(string asName)
    {
        return base.Channel.JoinAsync(asName);
    }

    public void Leave()
    {
        base.Channel.Leave();
    }

    public System.Threading.Tasks.Task LeaveAsync()
    {
        return base.Channel.LeaveAsync();
    }
}
